language = "en"
open_last_loaded_on_startup = true
generate_thumbs = true
thumb_cache_size = 500.0
cached_thumb_quality = 80
cached_thumb_resolution = 256
autoplay = true
loop = true
show_filenames_in_grid = true
page_size = 100
infinite_scroll = true
show_filepath = 1
tag_click_action = 2
theme = 2
splash = "default"
windows_start_command = false
date_format = "%x"
hour_format = true
zero_padding = true
